spring:
  application:
    name: ahun-bff

server:
  port: 8080

feign:
  client:
    config:
      users:
        loggerLevel: full
        connectTimeout: 3000
        readTimeout: 3000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


integracoes:
  integrantes: http://localhost:8081
